// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3N-6K9dYMegG8zZ23L0UcPjKMQO8AEtM',
    appId: '1:1034860115167:web:e1f9ac1967ac0f31f2656a',
    messagingSenderId: '1034860115167',
    projectId: 'visitasmuseosmx',
    authDomain: 'visitasmuseosmx.firebaseapp.com',
    storageBucket: 'visitasmuseosmx.appspot.com',
    measurementId: 'G-JDCQHSZ1X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7UWdBDVnJeq_2cPl1nvggpa-G1Y5QMjk',
    appId: '1:1034860115167:android:e2aca6f95747cd20f2656a',
    messagingSenderId: '1034860115167',
    projectId: 'visitasmuseosmx',
    storageBucket: 'visitasmuseosmx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ7E12qkyxGXBx3MNSST0__ldJvPFh1NM',
    appId: '1:1034860115167:ios:18d75872dc9adf4af2656a',
    messagingSenderId: '1034860115167',
    projectId: 'visitasmuseosmx',
    storageBucket: 'visitasmuseosmx.appspot.com',
    iosBundleId: 'com.example.applesly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ7E12qkyxGXBx3MNSST0__ldJvPFh1NM',
    appId: '1:1034860115167:ios:18d75872dc9adf4af2656a',
    messagingSenderId: '1034860115167',
    projectId: 'visitasmuseosmx',
    storageBucket: 'visitasmuseosmx.appspot.com',
    iosBundleId: 'com.example.applesly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3N-6K9dYMegG8zZ23L0UcPjKMQO8AEtM',
    appId: '1:1034860115167:web:d7ca2cde2dae5cfbf2656a',
    messagingSenderId: '1034860115167',
    projectId: 'visitasmuseosmx',
    authDomain: 'visitasmuseosmx.firebaseapp.com',
    storageBucket: 'visitasmuseosmx.appspot.com',
    measurementId: 'G-8TQCL6T4W3',
  );
}
